/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RfidRouteImport } from './routes/rfid'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminFinesRouteImport } from './routes/admin.fines'
import { Route as AdminBooksRouteImport } from './routes/admin.books'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RfidRoute = RfidRouteImport.update({
  id: '/rfid',
  path: '/rfid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinesRoute = AdminFinesRouteImport.update({
  id: '/fines',
  path: '/fines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/rfid': typeof RfidRoute
  '/user': typeof UserRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rfid': typeof RfidRoute
  '/user': typeof UserRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/rfid': typeof RfidRoute
  '/user': typeof UserRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/rfid'
    | '/user'
    | '/admin/books'
    | '/admin/fines'
    | '/admin/students'
    | '/admin/transactions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rfid'
    | '/user'
    | '/admin/books'
    | '/admin/fines'
    | '/admin/students'
    | '/admin/transactions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/rfid'
    | '/user'
    | '/admin/books'
    | '/admin/fines'
    | '/admin/students'
    | '/admin/transactions'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RfidRoute: typeof RfidRoute
  UserRoute: typeof UserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfid': {
      id: '/rfid'
      path: '/rfid'
      fullPath: '/rfid'
      preLoaderRoute: typeof RfidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fines': {
      id: '/admin/fines'
      path: '/fines'
      fullPath: '/admin/fines'
      preLoaderRoute: typeof AdminFinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminFinesRoute: typeof AdminFinesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminFinesRoute: AdminFinesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RfidRoute: RfidRoute,
  UserRoute: UserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
