/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BooksIdRouteImport } from './routes/books.$id'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminFinesRouteImport } from './routes/admin.fines'
import { Route as AdminBooksRouteImport } from './routes/admin.books'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinesRoute = AdminFinesRouteImport.update({
  id: '/fines',
  path: '/fines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/books/$id': typeof BooksIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/books/$id': typeof BooksIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/signup': typeof SignupRoute
  '/user': typeof UserRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/fines': typeof AdminFinesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/books/$id': typeof BooksIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/login'
    | '/payments'
    | '/profile'
    | '/scanner'
    | '/signup'
    | '/user'
    | '/admin/books'
    | '/admin/fines'
    | '/admin/payments'
    | '/admin/students'
    | '/admin/transactions'
    | '/books/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/login'
    | '/payments'
    | '/profile'
    | '/scanner'
    | '/signup'
    | '/user'
    | '/admin/books'
    | '/admin/fines'
    | '/admin/payments'
    | '/admin/students'
    | '/admin/transactions'
    | '/books/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/login'
    | '/payments'
    | '/profile'
    | '/scanner'
    | '/signup'
    | '/user'
    | '/admin/books'
    | '/admin/fines'
    | '/admin/payments'
    | '/admin/students'
    | '/admin/transactions'
    | '/books/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  ScannerRoute: typeof ScannerRoute
  SignupRoute: typeof SignupRoute
  UserRoute: typeof UserRoute
  BooksIdRoute: typeof BooksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fines': {
      id: '/admin/fines'
      path: '/fines'
      fullPath: '/admin/fines'
      preLoaderRoute: typeof AdminFinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminFinesRoute: typeof AdminFinesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminFinesRoute: AdminFinesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  ScannerRoute: ScannerRoute,
  SignupRoute: SignupRoute,
  UserRoute: UserRoute,
  BooksIdRoute: BooksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
